general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid multiple instances of hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on displays after waking
}

# Screenlock after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Turn off monitors after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend PC after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
